### ISSUE TITLE
Add Support For SFX Not Attached to Trait

### ISSUE THREAD

**Issue by lynn0702** [kaelri/cortex-toolkit#2]
Support Adding SFX to a Trait Set instead only to a Trait.

**Comment by kaelri** [comment]
@lynn0702 Thanks for opening the issue! Clarifying question: if an SFX is attached directly to the trait set, would you expect it to:

1. Render recursively under each trait in the set? (Would this be a way to apply “Hinder” to distinctions, for example?)
2. Render in a separate location before or after the list of traits?
3. Something else?

**Comment by lynn0702** [comment]
I'd expect it to render below any traits in the set similar to a power set.
